In [1]:
# Matthew Berning
# Dependencies
import numpy as np
import pandas as pd

In [2]:
election_dataset = pd.read_csv('../database/data_retrieval_clean.csv')
election_dataset.head()

st_abbrev  district party  Total_Receipt  Total_Disbursement  \
0        AK         0   REP        1041380             1159940   
1        AL         1   REP        1325140              662806   
2        AL         2   REP        2506890             2100810   
3        AL         3   REP        1219670              857764   
4        AL         4   REP        1487010              853026   

   Cash_On_Hand_COP  Debt_Owed_By_Committee  Individual_Itemized_Contribution  \
0          151165.0                     0.0                          513967.0   
1         1108650.0                     0.0                          264612.0   
2          451536.0                     0.0                          741087.0   
3          887448.0                     0.0                          450890.0   
4         1099490.0                     0.0                          430365.0   

   Individual_Unitemized_Contribution  Individual_Contribution     ...      \
0                             41063.9                 555031.0     ...       
1                             10105.0                 274717.0     ...       
2                             46129.8                 787217.0     ...       
3                              9667.0                 460557.0     ...       
4                             23449.0                 453814.0     ...       

   Management_of_companies_and_enterprises3  \
0                                       193   
1                                       111   
2                                        85   
3                                        47   
4                                        76   

   Admin_and_support_and_waste_mngmt_and_remediation_services3  \
0                                               1128             
1                                                749             
2                                                578             
3                                                521             
4                                                401             

   Educational_services3  Health_care_and_social_assistance3  \
0                    270                                2633   
1                    144                                1427   
2                    131                                1538   
3                     89                                1142   
4                     58                                1548   

   Arts__entertainment__and_recreation3  Accommodation_and_food_services3  \
0                                   569                              2156   
1                                   198                              1331   
2                                   159                              1347   
3                                    94                              1186   
4                                   135                              1060   

   Other_services_except_public_administration3  Industries_not_classified3  \
0                                          1823                          40   
1                                          1663                          21   
2                                          1673                          29   
3                                          1402                          21   
4                                          1440                          30   

   Industries_not_classified4  state_dist  
0                           0       AK_00  
1                           0       AL_01  
2                           0       AL_02  
3                           0       AL_03  
4                           0       AL_04  

[5 rows x 329 columns]

In [3]:
election_dataset = election_dataset.drop(['id','st_abbrev', 'district', "Industries_not_classified4", "state_dist"], axis=1)

In [4]:
election_dataset.head()

party  Total_Receipt  Total_Disbursement  Cash_On_Hand_COP  \
0   REP        1041380             1159940          151165.0   
1   REP        1325140              662806         1108650.0   
2   REP        2506890             2100810          451536.0   
3   REP        1219670              857764          887448.0   
4   REP        1487010              853026         1099490.0   

   Debt_Owed_By_Committee  Individual_Itemized_Contribution  \
0                     0.0                          513967.0   
1                     0.0                          264612.0   
2                     0.0                          741087.0   
3                     0.0                          450890.0   
4                     0.0                          430365.0   

   Individual_Unitemized_Contribution  Individual_Contribution  \
0                             41063.9                 555031.0   
1                             10105.0                 274717.0   
2                             46129.8                 787217.0   
3                              9667.0                 460557.0   
4                             23449.0                 453814.0   

   Other_Committee_Contribution  Party_Committee_Contribution  \
0                      481912.0                          0.00   
1                      985650.0                        663.98   
2                     1628590.0                       5000.00   
3                      742720.0                      11500.00   
4                     1020840.0                          0.00   

              ...              Real_estate_and_rental_and_leasing3  \
0             ...                                              933   
1             ...                                              846   
2             ...                                              561   
3             ...                                              462   
4             ...                                              385   

   Professional__scientific__and_technical_services3  \
0                                               1960   
1                                               1420   
2                                               1249   
3                                                853   
4                                                808   

   Management_of_companies_and_enterprises3  \
0                                       193   
1                                       111   
2                                        85   
3                                        47   
4                                        76   

   Admin_and_support_and_waste_mngmt_and_remediation_services3  \
0                                               1128             
1                                                749             
2                                                578             
3                                                521             
4                                                401             

   Educational_services3  Health_care_and_social_assistance3  \
0                    270                                2633   
1                    144                                1427   
2                    131                                1538   
3                     89                                1142   
4                     58                                1548   

   Arts__entertainment__and_recreation3  Accommodation_and_food_services3  \
0                                   569                              2156   
1                                   198                              1331   
2                                   159                              1347   
3                                    94                              1186   
4                                   135                              1060   

   Other_services_except_public_administration3  Industries_not_classified3  
0                                          1823                          40  
1       

In [39]:
X = election_dataset.drop("party", axis=1)
y = election_dataset["party"]
print(X.shape, y.shape)

(434, 323) (434,)


In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [41]:
from keras.models import Sequential
from keras.layers import Dense

# Create model and add layers
model = Sequential()
model.add(Dense(units=500, activation='relu', input_dim=323))
model.add(Dense(units=500, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [42]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=2,
    shuffle=True,
    verbose=2
)

Epoch 1/2
 - 0s - loss: 0.4476 - acc: 0.8031
Epoch 2/2
 - 0s - loss: 0.1823 - acc: 0.9415


In [43]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Normal Neural Network - Loss: 0.5398270422165546, Accuracy: 0.8623853221945806


In [44]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

C:\Users\OI\Anaconda3\envs\PythonData\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [45]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test[:10])}")

Predicted classes: ['REP' 'DEM' 'DEM' 'REP' 'DEM' 'DEM' 'DEM' 'REP' 'DEM' 'DEM']
Actual Labels: ['REP', 'REP', 'DEM', 'REP', 'DEM', 'DEM', 'DEM', 'REP', 'DEM', 'DEM']


In [59]:
election_dataset.head(10)

party  Total_Receipt  Total_Disbursement  Cash_On_Hand_COP  \
0   REP        1041380             1159940          151165.0   
1   REP        1325140              662806         1108650.0   
2   REP        2506890             2100810          451536.0   
3   REP        1219670              857764          887448.0   
4   REP        1487010              853026         1099490.0   
5   REP        1474730             1876240          769423.0   
6   REP        1187160             1318790          520549.0   
7   DEM        1634560             1028350         1570730.0   
8   REP         974708              766218          467067.0   
9   REP        2724800             2843740          529730.0   

   Debt_Owed_By_Committee  Individual_Itemized_Contribution  \
0                     0.0                          513967.0   
1                     0.0                          264612.0   
2                     0.0                          741087.0   
3                     0.0                          450890.0   
4                     0.0                          430365.0   
5                     0.0                          839654.0   
6                     0.0                          280080.0   
7                     0.0                          301292.0   
8                     0.0                          456975.0   
9                     0.0                         1474510.0   

   Individual_Unitemized_Contribution  Individual_Contribution  \
0                            41063.90                 555031.0   
1                            10105.00                 274717.0   
2                            46129.80                 787217.0   
3                             9667.00                 460557.0   
4                            23449.00                 453814.0   
5                           359460.00                1199120.0   
6                             5130.01                 285210.0   
7                            15146.00                 316438.0   
8                            48195.60                 505171.0   
9                            78661.00                1553170.0   

   Other_Committee_Contribution  Party_Committee_Contribution  \
0                      481912.0                          0.00   
1                      985650.0                        663.98   
2                     1628590.0                       5000.00   
3                      742720.0                      11500.00   
4                     1020840.0                          0.00   
5                      270895.0                          0.00   
6                      299193.0                          0.00   
7                     1316800.0                         88.23   
8                      464688.0                       4850.00   
9                     1164580.0                       7050.00   

              ...              Real_estate_and_rental_and_leasing3  \
0             ...                                              933   
1             ...                                              846   
2             ...                                              561   
3             ...                                              462   
4             ...                                              385   
5             ...                                              700   
6             ...                                              701   
7             ...                                              559   
8             ...                                              570   
9             ...                                              948   

   Professional__scientific__and_technical_services3  \
0                                               1960   
1                                               1420   
2                                               1249   
3                                                853   
4                                                808   
5                                               1964 

In [46]:
election_dataset_minus_label = election_dataset.drop(['party'], axis=1)
election_dataset_minus_label.head(1)

Total_Receipt  Total_Disbursement  Cash_On_Hand_COP  \
0        1041380             1159940          151165.0   

   Debt_Owed_By_Committee  Individual_Itemized_Contribution  \
0                     0.0                          513967.0   

   Individual_Unitemized_Contribution  Individual_Contribution  \
0                             41063.9                 555031.0   

   Other_Committee_Contribution  Party_Committee_Contribution  \
0                      481912.0                           0.0   

   Cand_Contribution             ...              \
0                0.0             ...               

   Real_estate_and_rental_and_leasing3  \
0                                  933   

   Professional__scientific__and_technical_services3  \
0                                               1960   

   Management_of_companies_and_enterprises3  \
0                                       193   

   Admin_and_support_and_waste_mngmt_and_remediation_services3  \
0                                               1128             

   Educational_services3  Health_care_and_social_assistance3  \
0                    270                                2633   

   Arts__entertainment__and_recreation3  Accommodation_and_food_services3  \
0                                   569                              2156   

   Other_services_except_public_administration3  Industries_not_classified3  
0                                          1823                          40  

[1 rows x 323 columns]

In [68]:
all_values_list = election_dataset_minus_label.values.tolist()

test1 = all_values_list[0]
test2 = all_values_list[1]
test3 = all_values_list[2]
test4 = all_values_list[3]
test5 = all_values_list[7]

all_values_scaled = X_scaler.transform(all_values_list)

In [69]:
import numpy
from numpy import array
test1_a = np.array([test1])
test2_a = np.array([test2])
test3_a = np.array([test3])
test4_a = np.array([test4])
test5_a = np.array([test5])

all_values_a = np.array(all_values_scaled)



In [70]:
model.predict(all_values_scaled, verbose=1)

434/434 [==============================] - 0s 50us/step


array([[8.95153344e-01, 1.04846723e-01],
       [6.17437670e-03, 9.93825674e-01],
       [7.15194549e-03, 9.92848039e-01],
       [9.74215660e-03, 9.90257859e-01],
       [7.67953694e-03, 9.92320478e-01],
       [1.84698105e-02, 9.81530249e-01],
       [3.74752609e-03, 9.96252477e-01],
       [9.82782960e-01, 1.72169711e-02],
       [6.22665742e-03, 9.93773401e-01],
       [6.04531020e-02, 9.39546883e-01],
       [2.66534444e-02, 9.73346531e-01],
       [1.34505471e-02, 9.86549437e-01],
       [5.33218682e-01, 4.66781318e-01],
       [8.28072608e-01, 1.71927407e-01],
       [9.91780698e-01, 8.21931567e-03],
       [7.22839759e-05, 9.99927759e-01],
       [4.71446337e-03, 9.95285571e-01],
       [9.23763886e-02, 9.07623649e-01],
       [9.99958515e-01, 4.14349270e-05],
       [6.28131479e-02, 9.37186897e-01],
       [9.97003973e-01, 2.99599324e-03],
       [5.78257143e-02, 9.42174256e-01],
       [9.98892009e-01, 1.10803801e-03],
       [9.98123586e-01, 1.87634351e-03],
       [1.000000

In [50]:
model.predict_proba(test2_a, batch_size=32, verbose=1)

1/1 [==============================] - 0s 0us/step


array([[1., 0.]], dtype=float32)

In [51]:
model.predict_proba(test3_a, batch_size=32, verbose=0)

array([[1., 0.]], dtype=float32)

In [52]:
model.predict_proba(test4_a, batch_size=32, verbose=0)

array([[1., 0.]], dtype=float32)

In [61]:
a = model.predict_proba(test5_a, batch_size=32, verbose=0)

In [62]:
a

array([[1., 0.]], dtype=float32)

In [54]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 500)               162000    
_________________________________________________________________
dense_5 (Dense)              (None, 500)               250500    
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 1002      
Total params: 413,502
Trainable params: 413,502
Non-trainable params: 0
_________________________________________________________________
